services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./cinema-schedule
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cinema
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

  frontend:
    build:
      context: ./cinema-frontend
    ports:
      - "4200:4200"
    restart: always
